version: '3.4'

services:
  db:
    image: postgres:15.0-alpine
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=rest_with_asp_net_udemy
    ports:
      - '5438:5432'
    networks:
      - udemy-network
    volumes: 
      - db:/var/lib/postgresql/data
  rest-with-asp-net-udemy:
    image: rest-with-asp-net-udemy
    build:
      context: .
      dockerfile: RestWithASPNETUdemy/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - '5001:80'
    depends_on:
      - db
    networks:
      - udemy-network
networks:
  udemy-network:
    driver: bridge
volumes:
  db:
    driver: local